// src/client/components/spotify/current-track.tsx
import {
  type Dispatch,
  type SetStateAction,
  useEffect,
  useEffectEvent,
  useRef,
  useState
} from "react"

import { cn } from "@/client/lib/utils"

import WaveForm from "./wave-form"

type Track = {
  artist: string
  cover: string
  externalUrl: string
  name: string
}

function calculateDuration(distance: number) {
  if (distance <= 0) {
    return 0
  }

  const seconds = distance / 15
  return Math.min(Math.max(seconds, 6), 18)
}

export default function CurrentTrack({
  sheetTileClass = "",
  variant = "floating"
}: {
  sheetTileClass?: string
  variant?: "floating" | "sheet"
}) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [delayedExpanded, setDelayedExpanded] = useState(false)
  const [shouldScrollTrack, setShouldScrollTrack] = useState(false)
  const [shouldScrollArtist, setShouldScrollArtist] = useState(false)
  const [trackScrollDistance, setTrackScrollDistance] = useState(0)
  const [artistScrollDistance, setArtistScrollDistance] = useState(0)
  const [track, setTrack] = useState<Track | null>(null)
  const timerRef = useRef<number | null>(null)
  const intervalRef = useRef<number | null>(null)
  const trackNameWrapperRef = useRef<HTMLSpanElement | null>(null)
  const trackNameTextRef = useRef<HTMLSpanElement | null>(null)
  const artistNameWrapperRef = useRef<HTMLSpanElement | null>(null)
  const artistNameTextRef = useRef<HTMLSpanElement | null>(null)

  const isSheetVariant = variant === "sheet"

  const updateMarqueeFor = (
    wrapper: HTMLElement | null,
    textElement: HTMLElement | null,
    setShouldScroll: Dispatch<SetStateAction<boolean>>,
    setDistance: Dispatch<SetStateAction<number>>
  ) => {
    if (!wrapper || !textElement) {
      setShouldScroll(false)
      setDistance(0)
      return
    }

    const overflow = textElement.scrollWidth - wrapper.clientWidth
    setShouldScroll(overflow > 4)
    setDistance(Math.max(overflow, 0))
  }

  const scheduleMarqueeMeasurement = useEffectEvent(() => {
    if (!track || (!isSheetVariant && !delayedExpanded)) {
      return
    }

    window.requestAnimationFrame(() => {
      updateMarqueeFor(
        trackNameWrapperRef.current,
        trackNameTextRef.current,
        setShouldScrollTrack,
        setTrackScrollDistance
      )
      updateMarqueeFor(
        artistNameWrapperRef.current,
        artistNameTextRef.current,
        setShouldScrollArtist,
        setArtistScrollDistance
      )
    })
  })

  useEffect(() => {
    scheduleMarqueeMeasurement()
  }, [delayedExpanded, isSheetVariant, scheduleMarqueeMeasurement, track])

  useEffect(() => {
    const handleResize = () => {
      scheduleMarqueeMeasurement()
    }

    window.addEventListener("resize", handleResize)

    return () => {
      window.removeEventListener("resize", handleResize)
    }
  }, [delayedExpanded, isSheetVariant, scheduleMarqueeMeasurement, track])

  useEffect(() => {
    if (isSheetVariant) {
      return
    }

    if (isExpanded) {
      timerRef.current = window.setTimeout(() => {
        setDelayedExpanded(true)
      }, 1000)
      scheduleMarqueeMeasurement()
      return
    }

    if (timerRef.current !== null) {
      window.clearTimeout(timerRef.current)
    }

    setDelayedExpanded(false)
    setShouldScrollTrack(false)
    setShouldScrollArtist(false)
  }, [isExpanded, isSheetVariant, scheduleMarqueeMeasurement, track])

  useEffect(() => {
    const fetchCurrentTrack = async () => {
      try {
        const response = await fetch(
          `${import.meta.env.VITE_BACKEND_URL}/spotify/current-track`
        )

        if (!response.ok) {
          throw new Error("Failed to fetch current track")
        }

        const data = (await response.json()) as Track

        if (!data.name) {
          throw new Error("No current track")
        }

        setTrack(data)
      } catch {
        setTrack(null)
      }
    }

    void fetchCurrentTrack()
    intervalRef.current = window.setInterval(fetchCurrentTrack, 30000)

    return () => {
      if (intervalRef.current !== null) {
        window.clearInterval(intervalRef.current)
      }

      if (timerRef.current !== null) {
        window.clearTimeout(timerRef.current)
      }
    }
  }, [])

  if (!track) {
    return null
  }

  const trackStyle = shouldScrollTrack
    ? {
        ["--scroll-distance" as string]: `${trackScrollDistance}px`,
        ["--scroll-duration" as string]: `${calculateDuration(trackScrollDistance)}s`
      }
    : undefined

  const artistStyle = shouldScrollArtist
    ? {
        ["--scroll-distance" as string]: `${artistScrollDistance}px`,
        ["--scroll-duration" as string]: `${calculateDuration(artistScrollDistance)}s`
      }
    : undefined

  if (isSheetVariant) {
    return (
      <a
        aria-label={`Listen to ${track.name} by ${track.artist} on Spotify`}
        className={cn(
          sheetTileClass,
          "group mb-6 max-w-full items-center gap-3 overflow-clip border-none bg-transparent px-0 py-0 normal-case tracking-normal no-underline hover:bg-transparent dark:bg-transparent dark:hover:bg-transparent"
        )}
        href={track.externalUrl}
        rel="noreferrer noopener"
        target="_blank"
      >
        <span className="relative flex size-9 items-center justify-center overflow-hidden rounded-full border border-zinc-200 bg-muted dark:border-zinc-800">
          <img
            alt={track.name}
            className="animate-spin-slow h-full w-full object-cover"
            src={track.cover}
          />
        </span>

        <span className="flex min-w-0 flex-1 flex-col gap-1 overflow-hidden text-left">
          <span className="flex justify-between text-[10px] font-semibold uppercase tracking-[0.35em] text-muted-foreground/70">
            Now listening to
            <span className="flex shrink-0 items-center pl-1 text-muted-foreground/80">
              <WaveForm />
            </span>
          </span>

          <span className="block w-full min-w-0 overflow-hidden whitespace-nowrap text-sm font-semibold text-foreground" ref={trackNameWrapperRef}>
            <span
              className={cn(
                "inline-flex items-center will-change-transform",
                shouldScrollTrack ? "animate-marquee" : ""
              )}
              ref={trackNameTextRef}
              style={trackStyle}
            >
              {track.name}
            </span>
          </span>

          <span className="block w-full min-w-0 overflow-hidden whitespace-nowrap text-[11px] font-medium text-muted-foreground" ref={artistNameWrapperRef}>
            <span
              className={cn(
                "inline-flex items-center will-change-transform",
                shouldScrollArtist ? "animate-marquee" : ""
              )}
              ref={artistNameTextRef}
              style={artistStyle}
            >
              {track.artist}
            </span>
          </span>
        </span>
      </a>
    )
  }

  return (
    <div
      className={cn(
        "fixed right-4 top-4 z-[2] hidden max-w-[calc(100%-2rem)] cursor-pointer rounded-full border border-zinc-200 bg-background/90 p-1 backdrop-blur-sm transition-[border-radius] duration-700 lg:flex dark:border-zinc-800 dark:bg-zinc-950/80",
        isExpanded ? "rounded-r-none" : ""
      )}
      onMouseEnter={() => setIsExpanded(true)}
      onMouseLeave={() => setIsExpanded(false)}
    >
      <a
        className="flex items-center border-none text-inherit no-underline"
        href={track.externalUrl}
        rel="noreferrer noopener"
        target="_blank"
      >
        <div className="h-[30px] w-[30px] shrink-0 overflow-hidden rounded-full bg-white/10">
          <img
            alt={track.name}
            className="animate-spin-slow h-full w-full object-cover"
            src={track.cover}
          />
        </div>

        <div
          className={cn(
            "overflow-hidden whitespace-nowrap text-xs transition-all duration-700",
            isExpanded ? "ml-2 w-[100px]" : "w-0"
          )}
        >
          <p className="m-0 flex flex-col leading-[1.2] text-foreground no-underline">
            <span className="block w-full min-w-0 overflow-hidden whitespace-nowrap" ref={trackNameWrapperRef}>
              <span
                className={cn(
                  "inline-flex items-center will-change-transform",
                  shouldScrollTrack ? "animate-marquee" : ""
                )}
                ref={trackNameTextRef}
                style={trackStyle}
              >
                {track.name}
              </span>
            </span>
            <span className="mt-px block w-full min-w-0 overflow-hidden whitespace-nowrap text-[0.65rem] opacity-70" ref={artistNameWrapperRef}>
              <span
                className={cn(
                  "inline-flex items-center will-change-transform",
                  shouldScrollArtist ? "animate-marquee" : ""
                )}
                ref={artistNameTextRef}
                style={artistStyle}
              >
                {track.artist}
              </span>
            </span>
          </p>
        </div>
      </a>

      <div className="absolute right-0 top-full mt-2 w-auto max-w-none whitespace-nowrap">
        <div
          className={cn(
            "flex translate-y-[-10px] items-center gap-1 text-xs text-gray-400 opacity-0 transition-all duration-500",
            delayedExpanded ? "translate-y-0 opacity-100" : ""
          )}
        >
          <p>Now playing on Spotify</p>
          <WaveForm />
        </div>
      </div>
    </div>
  )
}

// src/components/spotify/CurrentTrack.vue
<template>
  <div v-if="track" class="mini-player" @mouseenter="isExpanded = true" @mouseleave="isExpanded = false">
    <a :href="track.externalUrl" target="_blank">
      <div class="artwork-container">
        <img :src="track.cover" :alt="track.name" class="artwork spinning" />
      </div>

      <div class="info-container" :class="{ expanded: isExpanded }">
        <div class="info">
          <p class="track-link">
            {{ track.name }}
            <small>{{ track.artist }}</small>
          </p>
        </div>
      </div>
    </a>

    <div class="sub-info-wrapper">
      <transition name="fade-slide">
        <div v-if="delayedExpanded" class="sub-info-container flex gap-1 items-center text-gray-400 text-xs">
          <p>Now playing on Spotify</p>
          <WaveForm />
        </div>
      </transition>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, onMounted, watch } from "vue"
  import WaveForm from "./WaveForm.vue"

  const isExpanded = ref(false)
  const delayedExpanded = ref(false)
  let timer: number | null = null

  watch(isExpanded, (newVal) => {
    if (newVal) {
      timer = window.setTimeout(() => {
        delayedExpanded.value = true
      }, 1000)
    } else {
      if (timer !== null) {
        clearTimeout(timer)
      }
      delayedExpanded.value = false
    }
  })

  const track = ref()

  async function fetchCurrentTrack() {
    try {
      const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/spotify/current-track`)
      if (!response.ok) throw new Error("Failed to fetch current track")

      const data = await response.json()
      if (!data.name) throw new Error("No track data found")

      console.log(`Currently, I'm listening to ${data.name} by ${data.artist} 🎵`)
      track.value = data
    } catch {
      console.log("Currently, I'm not listening to anything.")
      track.value = null
    }
  }

  onMounted(() => {
    fetchCurrentTrack()
    setInterval(fetchCurrentTrack, 30000)
  })
</script>

<style scoped>
  .mini-player {
    z-index: 2;
    position: fixed;
    top: 1rem;
    right: 1rem;
    backdrop-filter: blur(8px);
    padding: 0.25rem;
    border-radius: 9999px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
    cursor: pointer;
    height: fit-content;
    width: fit-content;
    max-width: calc(100% - 2rem);
  }

  body.dark .mini-player:hover {
    background: rgba(255, 255, 255, 0.01);
  }

  .mini-player a {
    display: flex;
    align-items: center;
    text-decoration: none;
    border: none;
  }

  .artwork-container {
    width: 30px;
    height: 30px;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.1);
    overflow: hidden;
    flex-shrink: 0;
  }

  .artwork {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .spinning {
    animation: spin 20s linear infinite;
  }

  .info-container {
    max-width: 0;
    overflow: hidden;
    transition: all 0.8s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .info-container.expanded {
    max-width: 125px;
    margin-left: 0.75rem;
  }

  .info {
    padding-right: 0.75rem;
    font-size: 0.75rem;
    white-space: nowrap;
  }

  .track-link {
    display: flex;
    flex-direction: column;
    color: black;
    line-height: 1.2;
    margin: 0;
  }

  .track-link small {
    opacity: 0.7;
    font-size: 0.65rem;
    margin-top: 1px;
  }

  .sub-info-wrapper { 
    position: absolute; 
    right: 0; 
    top: 100%; 
    white-space: nowrap; 
    width: auto; 
    max-width: none;
    margin-top: 0.25rem;
  }

  .fade-slide-enter-active,
  .fade-slide-leave-active {
    transition: opacity 0.5s ease, transform 0.5s ease;
  }
  .fade-slide-enter-from,
  .fade-slide-leave-to {
    opacity: 0;
    transform: translateY(-10px);
  }
  .fade-slide-enter-to,
  .fade-slide-leave-from {
    opacity: 1;
    transform: translateY(0);
  }

  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }

  body.dark .track-link {
    color: white;
  }

  body.dark .mini-player {
    background: rgba(255, 255, 255, 0.01);
  }

  body.dark .mini-player:hover {
    background: rgba(255, 255, 255, 0.01);
  }

  @media (hover: hover) {
    .mini-player:hover {
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
    }
  }

  @media (max-width: 1024px) {
    .mini-player {
      position: relative;
      display: flex;
        width: fit-content;
      padding: 0.5rem;
      top: 0;
      right: 0;
      margin: auto 0 1rem 0;
    }

    .mini-player a {
      gap: 0.5rem;
      width: auto;
    }

    .info-container {
      width: auto;
      margin-left: 0;
      max-width: 300px;
    }

    .info {
      padding-right: 0.75rem;
    }
  }

  @media (max-width: 600px) {
    .info-container {
      max-width: 150px;
    }
  }
</style>
