// src/client/pages/FunPage.vue
<template>
  <div id="content" class="space-y-12 sm:pb-0 pb-16">
    <div class="flex flex-col">
      <div v-for="(project, projectIndex) in projects" :key="project.id">
        <div class="project-info space-y-3">
          <div class="flex items-center justify-between">
            <h3 class="flex gap-1 items-center font-semibold">
              <a
                v-if="project.link.includes('https')"
                :href="project.link"
                target="_blank"
                class="flex gap-1 items-center"
                >{{ project.title }}</a
              >
              <RouterLink
                v-else
                :to="project.link"
                class="flex gap-1 items-center"
              >
                {{ project.title }}
              </RouterLink>
            </h3>

            <p
              class="font-light text-sm lowercase text-neutral-400 dark:text-neutral-500"
            >
              {{ project.subtitle }}
            </p>
          </div>

          <p
            v-if="project.mobileDescription"
            class="text-sm text-neutral-600 dark:text-neutral-500 sm:hidden"
          >
            {{ project.mobileDescription }}
          </p>
          <p
            class="text-sm text-neutral-600 dark:text-neutral-500"
            :class="project.mobileDescription ? 'hidden sm:block' : ''"
            v-html="project.description"
          />

          <p class="text-xs text-neutral-400 my-2">
            <span v-if="project.date">{{ project.date }}</span>
          </p>
        </div>

        <!-- thematic break -->
        <div
          v-if="projectIndex !== projects.length - 1"
          class="border-b border-neutral-200 dark:border-neutral-800 my-8"
        />
      </div>
    </div>
    <!-- Strava activities -->
    <Activity />
  </div>
</template>

<script setup lang="ts">
  import { ref } from "vue"

  import Activity from "@/client/components/StravaActivity.vue"

  const projects = ref(
    [
      {
        id: 1,
        title: "tab-overflow",
        subtitle: "Overcoming the paradox of choice",
        description: `I come across tonnes of niche little articles on technical topics, general life advice and other bits and pieces. I use a chrome extension to save the links to a Notion database, but rarely get around to reading them. Just glancing at the <span class="font-mono">&gt;400</span> articles in there makes me shiver, so I got <span class="font-mono">gpt-4o</span> to summarise most of them, and built this front-end to bubble up one at random, with estimated reading time and a few tags.
        The hardest thing about the abundance of information today is deciding <a href="https://jeremy.zawodny.com/blog/archives/008581.html" target="_blank">what to ignore</a>.`,
        mobileDescription:
          "Surface a random summary from my 400+ saved reads, with tags and reading time so I actually pick one.",
        link: "/fun/tab-overflow",
        date: "2023-10 (updated 2025-11)"
      },
      {
        id: 2,
        title: "pgt",
        subtitle: "Paul Graham's Essays, Translated",
        description:
          "I noticed that some of Paul Graham's essays had translations in other languages. Not all of them were translated, and some of the translations were incomplete or dead links altogether. I decided to create a website that hosted translations of all his essays, translated into 8 languages, using 4 LLMs. I imagined that the people that would find this most useful were those that weren't aware of browsers' built-in translation features, so I heavily optimised for SEO and performance in Next.js with SSG. Learned a lot about SEO and performance in the process.",
        mobileDescription:
          "Hosts every Paul Graham essay in 8 languages, tuned for speed and SEO so readers can find a translation fast.",
        link: "https://paulgraham-translated.vercel.app",
        date: "2024-11"
      }
    ].reverse()
  )
</script>

// src/client/pages/fun-page.tsx
import { Link } from "react-router-dom"

import StravaActivity from "@/client/components/strava-activity"

const projects = [
  {
    date: "2024-11",
    description:
      "Hosts every Paul Graham essay in 8 languages, tuned for speed and SEO so readers can find a translation fast.",
    id: 2,
    link: "https://paulgraham-translated.vercel.app",
    mobileDescription:
      "Hosts every Paul Graham essay in 8 languages, tuned for speed and SEO so readers can find a translation fast.",
    title: "pgt"
  },
  {
    date: "2023-10 (updated 2025-11)",
    description: `Randomly surfaces one of my saved reads. The hardest thing about the abundance of information today is deciding <a href="https://jeremy.zawodny.com/blog/archives/008581.html" target="_blank">what to ignore</a>.`,
    id: 1,
    link: "/fun/tab-overflow",
    mobileDescription:
      "Surface a random summary from my 400+ saved reads, with tags and reading time so I actually pick one.",
    title: "tab-overflow"
  }
]

export default function FunPage() {
  return (
    <div className="mt-8 space-y-12 pb-16 sm:pb-0">
      <div className="flex flex-col">
        {projects.map((project, index) => (
          <div key={project.id}>
            <div className="space-y-3">
              <div className="flex items-center justify-between gap-4">
                <h3 className="flex items-center gap-1 font-semibold">
                  {project.link.startsWith("https") ? (
                    <a
                      className="flex items-center gap-1"
                      href={project.link}
                      target="_blank"
                    >
                      {project.title}
                    </a>
                  ) : (
                    <Link className="flex items-center gap-1" to={project.link}>
                      {project.title}
                    </Link>
                  )}
                </h3>

                <p className="my-2 text-xs text-neutral-400">{project.date}</p>
              </div>

              {project.mobileDescription ? (
                <p className="text-sm text-neutral-600 dark:text-neutral-500 sm:hidden">
                  {project.mobileDescription}
                </p>
              ) : null}

              <p
                className={
                  project.mobileDescription
                    ? "hidden text-sm text-neutral-600 dark:text-neutral-500 sm:block"
                    : "text-sm text-neutral-600 dark:text-neutral-500"
                }
                dangerouslySetInnerHTML={{ __html: project.description }}
              />
            </div>

            <div className="my-8 border-b border-neutral-200 dark:border-neutral-800" />
          </div>
        ))}
      </div>

      <StravaActivity />
    </div>
  )
}
