// src/client/pages/ProjectPage.vue
<template>
  <div id="content">
    <component :is="selectedComponent" v-if="selectedComponent" />
  </div>
</template>

<script setup lang="ts">
  import { type Component, onMounted, ref } from "vue"
  import { useRoute } from "vue-router"

  import ReadingSuggestion from "@/client/pages/TabOverflow.vue"

  const selectedComponent = ref<Component>()

  const selectComponent = () => {
    const route = useRoute()
    const routeName = (route.params.name as string).replace(":", "")

    const components = {
      ReadingSuggestion
    }

    switch (routeName) {
      case "tab-overflow":
        selectedComponent.value = components.ReadingSuggestion
        break
    }
  }

  onMounted(() => {
    selectComponent()
  })
</script>

// src/client/pages/project-page.tsx
import { useParams } from "react-router-dom"

import TabOverflow from "@/client/pages/tab-overflow"

const components = {
  "tab-overflow": TabOverflow
}

export default function ProjectPage() {
  const { name } = useParams()

  if (!name || !(name in components)) {
    return null
  }

  const SelectedComponent = components[name as keyof typeof components]

  return (
    <div className="mt-8">
      <SelectedComponent />
    </div>
  )
}
