// src/client/pages/TabOverflow.vue
<template>
  <div
    class="min-h-80 flex flex-col transition-all duration-1000 overflow-hidden"
  >
    <div
      v-if="isLoading"
      class="flex flex-1 flex-col items-center justify-center gap-4 py-8 transition-colors duration-1000"
    >
      <div class="w-full">
        <div
          class="border border-zinc-200 bg-white/80 p-6 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/60 animate-pulse"
        >
          <div class="h-4 w-24 rounded bg-gray-200 dark:bg-gray-700" />
          <div class="mt-6 h-6 w-3/4 rounded bg-gray-200 dark:bg-gray-700" />
          <div class="mt-3 h-4 w-full rounded bg-gray-200 dark:bg-gray-700" />
          <div class="mt-2 h-4 w-5/6 rounded bg-gray-200 dark:bg-gray-700" />
          <div class="mt-2 h-4 w-1/2 rounded bg-gray-200 dark:bg-gray-700" />
          <div class="mt-6 flex flex-wrap gap-2">
            <span class="block h-6 w-20 bg-gray-200 dark:bg-gray-700" />
            <span class="block h-6 w-16 bg-gray-200 dark:bg-gray-700" />
          </div>
          <div class="mt-6 flex flex-wrap gap-2">
            <span class="block h-9 w-28 bg-gray-200 dark:bg-gray-700" />
            <span class="block h-9 w-28 bg-gray-200 dark:bg-gray-700" />
            <span class="block h-9 w-32 bg-gray-200 dark:bg-gray-700" />
          </div>
        </div>
      </div>
    </div>

    <div
      v-else
      ref="suggestionCardRef"
      class="tab-overflow-suggestion flex flex-col items-center justify-center gap-2 my-8 flex-1"
    >
      <div class="mx-auto grid w-full max-w-4xl grid-cols-[auto_1fr_auto]">
        <Button
          type="button"
          variant="ghost"
          class="flex h-full cursor-pointer w-6 items-center justify-center rounded-none border border-r-0 border-zinc-200 bg-background/80 p-0 text-muted-foreground transition-colors hover:bg-muted/40 dark:border-zinc-800 dark:bg-zinc-900/70"
          :disabled="currentIndex <= 0"
          @click="prevSuggestion"
        >
          <ChevronLeft class="size-4" />
        </Button>

        <div
          class="relative mx-auto flex h-full w-full min-w-0 flex-col overflow-hidden border border-zinc-200 bg-background/80 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/70"
        >
          <div class="grid h-full min-w-0">
            <AnimatePresence :initial="false" :custom="transitionDirection">
              <Motion
                v-if="tabOverflowSuggestion.id"
                :key="tabOverflowSuggestion.id"
                tag="div"
                class="col-start-1 row-start-1 flex h-full w-full min-w-0 flex-col"
                :variants="cardVariants"
                :initial="'enter'"
                :animate="'center'"
                :exit="'exit'"
                :transition="cardTransition"
              >
                <header
                  class="flex w-full min-w-0 flex-nowrap items-center gap-4 overflow-hidden border-b border-zinc-200 py-3 px-4 dark:border-zinc-800"
                >
                  <a
                    :href="tabOverflowSuggestion.url"
                    target="_blank"
                    class="block min-w-0 flex-1 lowercase truncate text-md sm:text-lg font-semibold leading-tight text-foreground transition-colors hover:text-primary"
                  >
                    {{ tabOverflowSuggestion.name }}
                  </a>

                  <TooltipProvider>
                    <div class="flex shrink-0 items-center gap-2">
                      <Tooltip>
                        <TooltipTrigger as-child>
                          <Button
                            size="icon-sm"
                            variant="secondary"
                            class="rounded-none cursor-pointer"
                            @click="openCurrentLink"
                          >
                            <ArrowUpRight class="size-4" />
                          </Button>
                        </TooltipTrigger>
                        <TooltipContent side="bottom"
                          >open in new tab</TooltipContent
                        >
                      </Tooltip>

                      <Tooltip>
                        <TooltipTrigger as-child>
                          <Button
                            size="icon-sm"
                            :variant="isCurrentBookmarked ? 'default' : 'ghost'"
                            class="border border-transparent hover:border-primary/40 rounded-none cursor-pointer"
                            @click="toggleBookmarkForCurrent"
                          >
                            <BookmarkCheck
                              v-if="isCurrentBookmarked"
                              class="size-4"
                            />
                            <Bookmark v-else class="size-4" />
                          </Button>
                        </TooltipTrigger>
                        <TooltipContent side="bottom">
                          {{
                            isCurrentBookmarked
                              ? "remove bookmark"
                              : "save for later"
                          }}
                        </TooltipContent>
                      </Tooltip>
                    </div>
                  </TooltipProvider>
                </header>

                <section class="px-4 py-3 min-w-0">
                  <p
                    v-if="tabOverflowSuggestion.summary"
                    class="text-sm leading-relaxed text-muted-foreground sm:text-base line-clamp-5 min-h-[5lh]"
                  >
                    {{ tabOverflowSuggestion.summary }}
                  </p>
                  <p v-else class="text-sm italic text-muted-foreground">
                    No summary available for this suggestion yet.
                  </p>
                </section>

                <footer
                  class="flex min-w-0 flex-col gap-4 border-t border-zinc-200 px-5 py-5 text-xs text-muted-foreground dark:border-zinc-800 sm:flex-row sm:items-center sm:justify-between"
                >
                  <div class="flex flex-wrap items-center gap-1">
                    <span class="font-medium text-foreground">
                      reading time:
                    </span>
                    <span>
                      {{
                        tabOverflowSuggestion.readingTime
                          ? `${tabOverflowSuggestion.readingTime} minutes`
                          : "Not set"
                      }}
                    </span>
                  </div>
                  <div class="flex flex-wrap gap-2">
                    <span
                      v-for="(
                        category, index
                      ) in tabOverflowSuggestion.categories"
                      :key="index"
                      class="border lowercase border-zinc-300 px-2.5 py-1 text-xs font-medium text-foreground dark:border-zinc-700"
                    >
                      {{ category }}
                    </span>
                    <span
                      v-if="!tabOverflowSuggestion.categories.length"
                      class="border border-dashed border-zinc-300 px-2.5 py-1 text-xs"
                    >
                      No categories yet
                    </span>
                  </div>
                </footer>
              </Motion>
            </AnimatePresence>
          </div>
        </div>

        <Button
          type="button"
          variant="ghost"
          class="flex h-full cursor-pointer w-6 items-center justify-center rounded-none border border-l-0 border-zinc-200 bg-background/80 p-0 text-muted-foreground transition-colors hover:bg-muted/40 dark:border-zinc-800 dark:bg-zinc-900/70"
          @click="nextSuggestion"
        >
          <ChevronRight class="size-4" />
        </Button>
      </div>
      <span
        class="pointer-events-none font-mono font-semibold tracking-tight text-muted-foreground text-[10px]"
      >
        {{ currentItemNumber }} / {{ tabOverflowCount }}
      </span>
    </div>

    <!-- Full list of tab-overflow items -->
    <div class="mt-8 border-t border-zinc-200 pt-4 dark:border-zinc-800">
      <div class="flex flex-wrap items-center justify-between gap-2 h-8">
        <button
          class="gap-1 text-xs border-0 p-0 flex cursor-pointer items-center hover:text-primary font-semibold"
          @click="toggleTableVisibility"
        >
          {{ isTableVisible ? "hide all" : "show all" }}
          <ChevronDown v-if="isTableVisible" class="size-4" />
          <ChevronRight v-else class="size-4" />
        </button>

        <div
          ref="readingTimeFilterRoot"
          :class="
            cn(
              'relative items-center gap-2',
              isTableVisible ? 'flex' : 'hidden'
            )
          "
        >
          <span
            v-if="readingTimeFilterLabel"
            class="text-xs text-muted-foreground"
          >
            under {{ readingTimeFilterLabel }}
          </span>

          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger as-child>
                <Button
                  size="icon-sm"
                  :variant="selectedReadingTimeFilter ? 'secondary' : 'ghost'"
                  class="cursor-pointer"
                  @click="toggleReadingTimeFilterVisibility"
                >
                  <Hourglass class="size-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                filter by read time
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>

          <div
            v-if="isReadingTimeFilterOpen"
            class="absolute right-0 top-full z-10 mt-2 min-w-[160px] rounded-md border border-zinc-200 bg-background/95 p-2 shadow-lg backdrop-blur-sm dark:border-zinc-800 dark:bg-zinc-900/95"
          >
            <p
              class="px-1 pb-2 text-[11px] uppercase tracking-wide text-muted-foreground"
            >
              under
            </p>
            <div class="flex flex-col gap-1">
              <Button
                v-for="option in readingTimeOptions"
                :key="option.value"
                size="sm"
                variant="ghost"
                class="justify-start rounded-sm text-xs capitalize cursor-pointer"
                :class="
                  option.value === selectedReadingTimeFilter
                    ? 'bg-primary/10 text-primary hover:bg-primary/20'
                    : ''
                "
                @click="selectReadingTimeFilter(option.value)"
              >
                {{ option.label }}
              </Button>
            </div>
          </div>

          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger as-child>
                <Button
                  size="sm"
                  :variant="showOnlyBookmarked ? 'secondary' : 'ghost'"
                  class="gap-1 text-xs cursor-pointer"
                  @click="toggleBookmarkFilter"
                >
                  <BookmarkCheck class="size-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                filter by bookmarked
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
          <span class="text-xs text-gray-500 dark:text-gray-400">
            {{ bookmarkCount }} saved
          </span>
        </div>
      </div>

      <div
        v-if="isTableVisible"
        class="mt-4 overflow-hidden border-zinc-200 dark:border-zinc-800"
      >
        <div class="overflow-x-auto">
          <Table>
            <TableBody v-if="filteredTableItems.length">
              <TableRow
                v-for="row in filteredTableItems"
                :key="row.item.id"
                :class="[
                  'cursor-pointer transition-colors',
                  row.item.id === tabOverflowSuggestion.id
                    ? 'bg-primary/10 dark:bg-primary/20'
                    : 'hover:bg-muted/60 dark:hover:bg-zinc-800/70'
                ]"
                @click="openSuggestionFromTable(row.index)"
              >
                <TableCell
                  class="font-medium truncate lowercase max-w-[200px] sm:max-w-[300px] pr-4"
                >
                  {{ row.item.name }}
                </TableCell>
                <TableCell>
                  <span v-if="row.item.readingTime">
                    {{ row.item.readingTime }} min
                  </span>
                  <span v-else class="text-gray-500 dark:text-gray-400">
                    —
                  </span>
                </TableCell>
                <TableCell class="max-w-[200px] lowercase">
                  <div class="flex overflow-x-scroll gap-1 no-scrollbar">
                    <span
                      v-for="(category, index) in row.item.categories"
                      :key="`${row.item.id}-cat-${index}`"
                      class="bg-gray-200 px-2 py-0.5 text-[11px] font-medium dark:bg-zinc-800"
                    >
                      {{ category }}
                    </span>
                    <span
                      v-if="!row.item.categories.length"
                      class="text-xs text-gray-500 dark:text-gray-400"
                    >
                      —
                    </span>
                  </div>
                </TableCell>
                <TableCell class="text-right">
                  <div class="flex items-center justify-end gap-2">
                    <Button
                      size="icon-sm"
                      variant="ghost"
                      class="cursor-pointer"
                      @click.stop="toggleBookmarkById(row.item.id)"
                    >
                      <BookmarkCheck
                        v-if="isBookmarked(row.item.id)"
                        class="size-4"
                      />
                      <Bookmark v-else class="size-4" />
                    </Button>
                    <Button
                      size="icon-sm"
                      variant="ghost"
                      class="cursor-pointer"
                      @click.stop="openLink(row.item.url)"
                    >
                      <ArrowUpRight class="size-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            </TableBody>
            <TableBody v-else>
              <TableEmpty :colspan="4">
                <span class="text-sm text-gray-500 dark:text-gray-400">
                  No items to display. Try saving a bookmark first.
                </span>
              </TableEmpty>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { useQuery } from "@tanstack/vue-query"
  import {
    ArrowUpRight,
    Bookmark,
    BookmarkCheck,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Hourglass
  } from "lucide-vue-next"
  import { AnimatePresence, Motion } from "motion-v"
  import {
    computed,
    nextTick,
    onMounted,
    onUnmounted,
    ref,
    watch,
    watchEffect
  } from "vue"

  import { Button } from "@/client/components/ui/button"
  import {
    Table,
    TableBody,
    TableCell,
    TableEmpty,
    TableRow
  } from "@/client/components/ui/table"
  import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger
  } from "@/client/components/ui/tooltip"
  import { cn } from "@/client/lib/utils"

  // Define the type for the tab overflow suggestion based on the new schema
  interface TabOverflowSuggestion {
    id: string
    name: string // Guaranteed
    url: string // Guaranteed
    readingTime: number | null
    categories: string[]
    summary: string
  }

  // Define type for a tab overflow item
  interface TabOverflowItem {
    id: string
    properties: {
      Name?: { title: { plain_text: string }[] }
      Link?: { url: string }
      "Read Time"?: { number: number }
      Categories?: { multi_select: { name: string }[] }
      Summary?: { rich_text: { plain_text: string }[] }
    }
  }

  // Reactive references
  const tabOverflowSuggestion = ref<TabOverflowSuggestion>({
    id: "",
    name: "",
    url: "",
    readingTime: null,
    categories: [],
    summary: ""
  })

  const transitionDirection = ref<1 | -1>(1)
  const cardVariants = {
    enter: (direction: 1 | -1) => ({
      x: direction > 0 ? "100%" : "-100%"
    }),
    center: { x: "0%" },
    exit: (direction: 1 | -1) => ({
      x: direction > 0 ? "-100%" : "100%"
    })
  }
  const cardTransition = {
    duration: 0.6,
    ease: [0.16, 1, 0.3, 1] as const
  }

  const BOOKMARK_STORAGE_KEY = "tabOverflow:bookmarks"

  const bookmarkedIds = ref<string[]>([])
  const isTableVisible = ref(false)
  const showOnlyBookmarked = ref(false)
  const suggestionCardRef = ref<HTMLElement | null>(null)
  const readingTimeFilterRoot = ref<HTMLElement | null>(null)

  const readingTimeOptions = [
    { label: "5 min", value: 5 },
    { label: "10 min", value: 10 },
    { label: "20 min", value: 20 }
  ] as const

  type ReadingTimeValue = (typeof readingTimeOptions)[number]["value"]

  const selectedReadingTimeFilter = ref<ReadingTimeValue | null>(null)
  const isReadingTimeFilterOpen = ref(false)

  const toggleReadingTimeFilterVisibility = () => {
    isReadingTimeFilterOpen.value = !isReadingTimeFilterOpen.value
  }

  const selectReadingTimeFilter = (value: ReadingTimeValue) => {
    selectedReadingTimeFilter.value =
      selectedReadingTimeFilter.value === value ? null : value
    isReadingTimeFilterOpen.value = false
  }

  const readingTimeFilterLabel = computed(() => {
    const match = readingTimeOptions.find(
      (option) => option.value === selectedReadingTimeFilter.value
    )
    return match?.label ?? ""
  })

  const fetchTabOverflow = async (): Promise<TabOverflowItem[]> => {
    const response = await fetch(
      `${import.meta.env.VITE_BACKEND_URL}/tab-overflow`,
      {
        method: "GET"
      }
    )

    if (!response.ok) {
      throw new Error("Network response was not ok")
    }

    return (await response.json()) as TabOverflowItem[]
  }

  const { data, isLoading } = useQuery({
    queryKey: ["tab-overflow"],
    queryFn: fetchTabOverflow,
    refetchOnWindowFocus: false
  })

  const tabOverflowItems = computed(() => data.value ?? [])

  const mapItemToSuggestion = (
    item: TabOverflowItem
  ): TabOverflowSuggestion => {
    const props = item.properties || {}
    const name = props.Name?.title?.[0]?.plain_text || "Untitled"
    const url = props.Link?.url || "#"
    const readingTime = props["Read Time"]?.number || null
    const categories = props.Categories?.multi_select
      ? props.Categories.multi_select.map((cat) => cat.name)
      : []
    const summary = props.Summary?.rich_text
      ? props.Summary.rich_text.map((txt) => txt.plain_text).join(" ")
      : ""

    return {
      id: item.id,
      name,
      url,
      readingTime,
      categories,
      summary
    }
  }

  const normalizedTabOverflowItems = computed(() =>
    tabOverflowItems.value.map((item) => mapItemToSuggestion(item))
  )

  // History for navigation (storing indices) and pointer
  const suggestionHistory = ref<number[]>([])
  const currentIndex = ref(-1)

  const currentItemNumber = computed(() => {
    if (currentIndex.value >= 0 && suggestionHistory.value.length > 0) {
      return suggestionHistory.value[currentIndex.value] + 1
    }
    return 0
  })

  const tabOverflowCount = computed(
    () => normalizedTabOverflowItems.value.length
  )

  const bookmarkCount = computed(() => bookmarkedIds.value.length)

  // Helper: Apply a suggestion from a given index
  const applySuggestionFromIndex = (index: number) => {
    const item = normalizedTabOverflowItems.value[index]
    if (!item) {
      return
    }

    tabOverflowSuggestion.value = { ...item }
  }

  // Choose a random index from the tab overflow items
  const chooseRandomIndex = (): number => {
    return Math.floor(Math.random() * normalizedTabOverflowItems.value.length)
  }

  // Navigate to the next suggestion
  const nextSuggestion = () => {
    if (!normalizedTabOverflowItems.value.length) {
      return
    }

    transitionDirection.value = 1
    // If we've navigated back previously, move forward in history if possible
    if (currentIndex.value < suggestionHistory.value.length - 1) {
      currentIndex.value++
      applySuggestionFromIndex(suggestionHistory.value[currentIndex.value])
    } else {
      let randomIndex = chooseRandomIndex()
      // Avoid duplicate if possible
      if (
        suggestionHistory.value.length > 0 &&
        normalizedTabOverflowItems.value.length > 1
      ) {
        while (
          randomIndex ===
          suggestionHistory.value[suggestionHistory.value.length - 1]
        ) {
          randomIndex = chooseRandomIndex()
        }
      }
      suggestionHistory.value.push(randomIndex)
      currentIndex.value = suggestionHistory.value.length - 1
      applySuggestionFromIndex(randomIndex)
    }
  }

  // Navigate to the previous suggestion if available
  const prevSuggestion = () => {
    if (currentIndex.value > 0) {
      transitionDirection.value = -1
      currentIndex.value--
      applySuggestionFromIndex(suggestionHistory.value[currentIndex.value])
    }
  }

  // Key event listener for arrow keys
  const handleKeydown = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft") {
      prevSuggestion()
    } else if (e.key === "ArrowRight") {
      nextSuggestion()
    }
  }

  const isBookmarked = (id: string) => bookmarkedIds.value.includes(id)

  const persistBookmarks = () => {
    if (typeof window === "undefined") {
      return
    }
    window.localStorage.setItem(
      BOOKMARK_STORAGE_KEY,
      JSON.stringify(bookmarkedIds.value)
    )
  }

  const loadBookmarks = () => {
    if (typeof window === "undefined") {
      return
    }
    try {
      const stored = window.localStorage.getItem(BOOKMARK_STORAGE_KEY)
      if (!stored) {
        return
      }
      const parsed = JSON.parse(stored)
      if (Array.isArray(parsed)) {
        bookmarkedIds.value = parsed.filter(
          (value): value is string => typeof value === "string"
        )
      }
    } catch (error) {
      console.error("Failed to load Tab Overflow bookmarks", error)
    }
  }

  const filterInvalidBookmarks = () => {
    const availableIds = new Set(
      normalizedTabOverflowItems.value.map((item) => item.id)
    )
    const filtered = bookmarkedIds.value.filter((id) => availableIds.has(id))
    if (filtered.length !== bookmarkedIds.value.length) {
      bookmarkedIds.value = filtered
      persistBookmarks()
    }
  }

  const isCurrentBookmarked = computed(() =>
    isBookmarked(tabOverflowSuggestion.value.id)
  )

  const toggleBookmarkById = (id: string) => {
    if (!id) {
      return
    }
    if (isBookmarked(id)) {
      bookmarkedIds.value = bookmarkedIds.value.filter(
        (bookmarkId) => bookmarkId !== id
      )
    } else {
      bookmarkedIds.value = [...bookmarkedIds.value, id]
    }
    persistBookmarks()
  }

  const toggleBookmarkForCurrent = () => {
    toggleBookmarkById(tabOverflowSuggestion.value.id)
  }

  const openLink = (url: string) => {
    if (!url || url === "#") {
      return
    }
    window.open(url, "_blank", "noopener")
  }

  const openCurrentLink = () => {
    openLink(tabOverflowSuggestion.value.url)
  }

  const toggleTableVisibility = () => {
    isTableVisible.value = !isTableVisible.value
  }

  const toggleBookmarkFilter = () => {
    showOnlyBookmarked.value = !showOnlyBookmarked.value
  }

  const handleReadingTimeFilterClickOutside = (event: MouseEvent) => {
    if (!isReadingTimeFilterOpen.value) {
      return
    }

    const root = readingTimeFilterRoot.value
    if (root && !root.contains(event.target as Node)) {
      isReadingTimeFilterOpen.value = false
    }
  }

  const filteredTableItems = computed(() => {
    const bookmarkSet = new Set(bookmarkedIds.value)
    return normalizedTabOverflowItems.value
      .map((item, index) => ({ item, index }))
      .filter(({ item }) =>
        showOnlyBookmarked.value ? bookmarkSet.has(item.id) : true
      )
      .filter(({ item }) => {
        if (selectedReadingTimeFilter.value === null) {
          return true
        }
        if (typeof item.readingTime !== "number") {
          return false
        }
        return item.readingTime < selectedReadingTimeFilter.value
      })
  })

  const openSuggestionFromTable = (index: number) => {
    if (index < 0 || index >= normalizedTabOverflowItems.value.length) {
      return
    }

    if (currentIndex.value >= 0) {
      const current = suggestionHistory.value[currentIndex.value]
      if (typeof current === "number") {
        transitionDirection.value = index >= current ? 1 : -1
      }
    } else {
      transitionDirection.value = 1
    }

    if (
      suggestionHistory.value.length === 0 ||
      suggestionHistory.value[suggestionHistory.value.length - 1] !== index
    ) {
      suggestionHistory.value.push(index)
    }
    currentIndex.value = suggestionHistory.value.length - 1
    applySuggestionFromIndex(index)
    nextTick(() => {
      scrollToSuggestionCard()
    })
  }

  const scrollToSuggestionCard = () => {
    if (typeof window === "undefined") {
      return
    }
    if (!suggestionCardRef.value) {
      window.scrollTo({ top: 0, behavior: "smooth" })
      return
    }
    const rect = suggestionCardRef.value.getBoundingClientRect()
    const viewportCenter = window.innerHeight / 2
    const target = window.scrollY + rect.top + rect.height / 2 - viewportCenter
    window.scrollTo({
      top: target > 0 ? target : 0,
      behavior: "smooth"
    })
  }

  // Kick off the first suggestion once data is ready
  watchEffect(() => {
    if (
      !isLoading.value &&
      currentIndex.value === -1 &&
      tabOverflowCount.value > 0
    ) {
      nextSuggestion()
    }
  })

  watch(normalizedTabOverflowItems, () => {
    filterInvalidBookmarks()
  })

  onMounted(() => {
    loadBookmarks()
    window.addEventListener("keydown", handleKeydown)
    if (typeof document !== "undefined") {
      document.addEventListener("click", handleReadingTimeFilterClickOutside)
    }
  })

  onUnmounted(() => {
    window.removeEventListener("keydown", handleKeydown)
    if (typeof document !== "undefined") {
      document.removeEventListener("click", handleReadingTimeFilterClickOutside)
    }
  })
</script>

// src/client/pages/tab-overflow.tsx
import { useQuery } from "@tanstack/react-query"
import {
  ArrowUpRight,
  Bookmark,
  BookmarkCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Hourglass
} from "lucide-react"
import { useEffect, useEffectEvent, useRef, useState } from "react"

import { cn } from "@/client/lib/utils"

type TabOverflowSuggestion = {
  added: Date | null
  categories: string[]
  id: string
  name: string
  readingTime: number | null
  summary: string
  url: string
}

type TabOverflowItem = {
  id: string
  properties: {
    Added?: { date?: { start?: string | null } | null; type: "date" }
    Categories?: { multi_select: { name: string }[] }
    Name?: { title: { plain_text: string }[] }
    "Read Time"?: { number: number }
    Summary?: { rich_text: { plain_text: string }[] }
    URL?: { url: string }
  }
}

const BOOKMARK_STORAGE_KEY = "tabOverflow:bookmarks"
const EMPTY_ITEMS: TabOverflowItem[] = []
const readingTimeOptions = [
  { label: "5 min", value: 5 },
  { label: "10 min", value: 10 },
  { label: "20 min", value: 20 }
] as const

type ReadingTimeValue = (typeof readingTimeOptions)[number]["value"]

function mapItemToSuggestion(item: TabOverflowItem): TabOverflowSuggestion {
  const props = item.properties ?? {}

  return {
    added:
      props.Added?.type === "date" && props.Added.date?.start
        ? new Date(props.Added.date.start)
        : null,
    categories:
      props.Categories?.multi_select?.map((category) => category.name) ?? [],
    id: item.id,
    name: props.Name?.title?.[0]?.plain_text || "Untitled",
    readingTime: props["Read Time"]?.number ?? null,
    summary:
      props.Summary?.rich_text?.map((text) => text.plain_text).join(" ") ?? "",
    url: props.URL?.url || "#"
  }
}

function loadBookmarks() {
  try {
    const stored = window.localStorage.getItem(BOOKMARK_STORAGE_KEY)

    if (!stored) {
      return []
    }

    const parsed = JSON.parse(stored)
    return Array.isArray(parsed)
      ? parsed.filter((value): value is string => typeof value === "string")
      : []
  } catch (error) {
    console.error("Failed to load Tab Overflow bookmarks", error)
    return []
  }
}

export default function TabOverflow() {
  const suggestionCardRef = useRef<HTMLDivElement | null>(null)
  const readingTimeFilterRootRef = useRef<HTMLDivElement | null>(null)
  const [bookmarkedIds, setBookmarkedIds] = useState<string[]>([])
  const [currentIndex, setCurrentIndex] = useState(-1)
  const [isReadingTimeFilterOpen, setIsReadingTimeFilterOpen] = useState(false)
  const [isTableVisible, setIsTableVisible] = useState(false)
  const [selectedReadingTimeFilter, setSelectedReadingTimeFilter] =
    useState<ReadingTimeValue | null>(null)
  const [showOnlyBookmarked, setShowOnlyBookmarked] = useState(false)
  const [suggestionHistory, setSuggestionHistory] = useState<number[]>([])
  const [tabOverflowSuggestion, setTabOverflowSuggestion] =
    useState<TabOverflowSuggestion>({
      added: null,
      categories: [],
      id: "",
      name: "",
      readingTime: null,
      summary: "",
      url: ""
    })

  const { data, isLoading } = useQuery({
    queryFn: async () => {
      const response = await fetch(
        `${import.meta.env.VITE_BACKEND_URL}/tab-overflow`
      )
      if (!response.ok) {
        throw new Error("Network response was not ok")
      }

      return (await response.json()) as TabOverflowItem[]
    },
    queryKey: ["tab-overflow"],
    refetchOnWindowFocus: false
  })

  const normalizedItems = (data ?? EMPTY_ITEMS).map(mapItemToSuggestion)
  const tabOverflowCount = normalizedItems.length
  const bookmarkCount = bookmarkedIds.length
  const isCurrentBookmarked = bookmarkedIds.includes(tabOverflowSuggestion.id)
  const readingTimeFilterLabel =
    readingTimeOptions.find(
      (option) => option.value === selectedReadingTimeFilter
    )?.label ?? ""

  const persistBookmarks = (nextBookmarkedIds: string[]) => {
    setBookmarkedIds(nextBookmarkedIds)
    window.localStorage.setItem(
      BOOKMARK_STORAGE_KEY,
      JSON.stringify(nextBookmarkedIds)
    )
  }

  const applySuggestionFromIndex = (index: number) => {
    const item = normalizedItems[index]
    if (item) {
      setTabOverflowSuggestion({ ...item })
    }
  }

  const chooseRandomIndex = () =>
    Math.floor(Math.random() * normalizedItems.length)

  const nextSuggestion = useEffectEvent(() => {
    if (!normalizedItems.length) {
      return
    }

    if (currentIndex < suggestionHistory.length - 1) {
      const nextIndex = currentIndex + 1
      setCurrentIndex(nextIndex)
      applySuggestionFromIndex(suggestionHistory[nextIndex])
      return
    }

    let randomIndex = chooseRandomIndex()
    if (suggestionHistory.length > 0 && normalizedItems.length > 1) {
      while (randomIndex === suggestionHistory[suggestionHistory.length - 1]) {
        randomIndex = chooseRandomIndex()
      }
    }

    const nextHistory = [...suggestionHistory, randomIndex]
    setSuggestionHistory(nextHistory)
    setCurrentIndex(nextHistory.length - 1)
    applySuggestionFromIndex(randomIndex)
  })

  const previousSuggestion = useEffectEvent(() => {
    if (currentIndex <= 0) {
      return
    }

    const nextIndex = currentIndex - 1
    setCurrentIndex(nextIndex)
    applySuggestionFromIndex(suggestionHistory[nextIndex])
  })

  const openLink = (url: string) => {
    if (!url || url === "#") {
      return
    }

    window.open(url, "_blank", "noopener")
  }

  const toggleBookmarkById = (id: string) => {
    if (!id) {
      return
    }

    if (bookmarkedIds.includes(id)) {
      persistBookmarks(bookmarkedIds.filter((bookmarkId) => bookmarkId !== id))
    } else {
      persistBookmarks([...bookmarkedIds, id])
    }
  }

  const filteredTableItems = normalizedItems
    .map((item, index) => ({ index, item }))
    .filter(({ item }) =>
      showOnlyBookmarked ? bookmarkedIds.includes(item.id) : true
    )
    .filter(({ item }) => {
      if (selectedReadingTimeFilter === null) {
        return true
      }

      if (typeof item.readingTime !== "number") {
        return false
      }

      return item.readingTime < selectedReadingTimeFilter
    })
    .sort(
      (a, b) => (b.item.added?.getTime() ?? 0) - (a.item.added?.getTime() ?? 0)
    )

  const scrollToSuggestionCard = () => {
    if (!suggestionCardRef.current) {
      window.scrollTo({ behavior: "smooth", top: 0 })
      return
    }

    const rect = suggestionCardRef.current.getBoundingClientRect()
    const viewportCenter = window.innerHeight / 2
    const target = window.scrollY + rect.top + rect.height / 2 - viewportCenter
    window.scrollTo({
      behavior: "smooth",
      top: target > 0 ? target : 0
    })
  }

  const openSuggestionFromTable = (index: number) => {
    if (index < 0 || index >= normalizedItems.length) {
      return
    }

    const nextHistory =
      suggestionHistory[suggestionHistory.length - 1] === index
        ? suggestionHistory
        : [...suggestionHistory, index]

    setSuggestionHistory(nextHistory)
    setCurrentIndex(nextHistory.length - 1)
    applySuggestionFromIndex(index)
    window.requestAnimationFrame(scrollToSuggestionCard)
  }

  useEffect(() => {
    setBookmarkedIds(loadBookmarks())
  }, [])

  useEffect(() => {
    const availableIds = new Set(normalizedItems.map((item) => item.id))
    const filteredBookmarks = bookmarkedIds.filter((id) => availableIds.has(id))
    if (filteredBookmarks.length !== bookmarkedIds.length) {
      persistBookmarks(filteredBookmarks)
    }
  }, [bookmarkedIds, normalizedItems])

  useEffect(() => {
    if (!isLoading && currentIndex === -1 && tabOverflowCount > 0) {
      nextSuggestion()
    }
  }, [currentIndex, isLoading, nextSuggestion, tabOverflowCount])

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if (event.key === "ArrowLeft") {
        previousSuggestion()
      }

      if (event.key === "ArrowRight") {
        nextSuggestion()
      }
    }

    const handleDocumentClick = (event: MouseEvent) => {
      if (
        isReadingTimeFilterOpen &&
        readingTimeFilterRootRef.current &&
        !readingTimeFilterRootRef.current.contains(event.target as Node)
      ) {
        setIsReadingTimeFilterOpen(false)
      }
    }

    window.addEventListener("keydown", handleKeydown)
    document.addEventListener("click", handleDocumentClick)

    return () => {
      window.removeEventListener("keydown", handleKeydown)
      document.removeEventListener("click", handleDocumentClick)
    }
  }, [isReadingTimeFilterOpen, nextSuggestion, previousSuggestion])

  return (
    <div className="flex min-h-[calc(100vh-8rem)] flex-col overflow-hidden transition-all duration-1000">
      <div className="flex min-h-[calc(100vh-12rem)] shrink-0 flex-col">
        {isLoading ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-4 py-8 transition-colors duration-1000">
            <div className="w-full">
              <div className="animate-pulse">
                <div className="h-4 w-24 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-6 h-6 w-3/4 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-3 h-4 w-full rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-2 h-4 w-5/6 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-2 h-4 w-1/2 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-6 flex flex-wrap gap-2">
                  <span className="block h-6 w-20 bg-gray-200 dark:bg-gray-700" />
                  <span className="block h-6 w-16 bg-gray-200 dark:bg-gray-700" />
                </div>
                <div className="mt-6 flex flex-wrap gap-2">
                  <span className="block h-9 w-28 bg-gray-200 dark:bg-gray-700" />
                  <span className="block h-9 w-28 bg-gray-200 dark:bg-gray-700" />
                  <span className="block h-9 w-32 bg-gray-200 dark:bg-gray-700" />
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div
            className="flex flex-1 flex-col items-center justify-center gap-2 py-8"
            ref={suggestionCardRef}
          >
            <div className="grid w-full grid-cols-[auto_1fr_auto] sm:block">
              <button
                className="flex h-full w-6 cursor-pointer items-center justify-center rounded-none border-0 bg-transparent p-0 text-muted-foreground transition-colors hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40 sm:hidden"
                disabled={currentIndex <= 0}
                onClick={previousSuggestion}
                type="button"
              >
                <ChevronLeft className="size-4" />
              </button>

              <div className="relative flex h-full w-full min-w-0 flex-col overflow-hidden border-0 bg-transparent">
                <div className="flex h-full w-full min-w-0 flex-col">
                  <header className="flex w-full min-w-0 flex-nowrap items-center gap-4 overflow-hidden">
                    <a
                      className="block min-w-0 flex-1 truncate text-md font-medium lowercase leading-tight text-foreground transition-colors hover:text-primary sm:text-lg"
                      href={tabOverflowSuggestion.url}
                      rel="noreferrer noopener"
                      target="_blank"
                    >
                      {tabOverflowSuggestion.name}
                    </a>

                    <div className="flex shrink-0 items-center gap-2">
                      <button
                        className="cursor-pointer rounded-none  bg-secondary p-2 text-foreground transition hover:bg-primary/10 dark:border-zinc-800"
                        onClick={() => openLink(tabOverflowSuggestion.url)}
                        title="open in new tab"
                        type="button"
                      >
                        <ArrowUpRight className="size-4" />
                      </button>

                      <button
                        className={cn(
                          "cursor-pointer rounded-none border p-2 transition",
                          isCurrentBookmarked
                            ? "border-primary/40 bg-primary/10 text-primary"
                            : "border-transparent bg-transparent text-foreground hover:border-primary/40"
                        )}
                        onClick={() =>
                          toggleBookmarkById(tabOverflowSuggestion.id)
                        }
                        title={
                          isCurrentBookmarked
                            ? "remove bookmark"
                            : "save for later"
                        }
                        type="button"
                      >
                        {isCurrentBookmarked ? (
                          <BookmarkCheck className="size-4" />
                        ) : (
                          <Bookmark className="size-4" />
                        )}
                      </button>
                    </div>
                  </header>

                  <section className="min-w-0 py-1">
                    {tabOverflowSuggestion.summary ? (
                      <p className="min-h-[5lh] line-clamp-5 text-sm leading-relaxed text-muted-foreground sm:text-base">
                        {tabOverflowSuggestion.summary}
                      </p>
                    ) : (
                      <p className="text-sm italic text-muted-foreground">
                        No summary available for this suggestion yet.
                      </p>
                    )}
                  </section>

                  <footer className="flex min-w-0 flex-col gap-3 py-1 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex flex-wrap items-center gap-1">
                      <span className="font-medium text-foreground">
                        reading time:
                      </span>
                      <span>
                        {tabOverflowSuggestion.readingTime
                          ? `${tabOverflowSuggestion.readingTime} minutes`
                          : "Not set"}
                      </span>
                    </div>

                    <div className="flex flex-wrap gap-2">
                      {tabOverflowSuggestion.categories.length ? (
                        tabOverflowSuggestion.categories.map((category) => (
                          <span
                            className="border border-zinc-300 px-2.5 py-1 text-xs font-medium lowercase text-foreground dark:border-zinc-700"
                            key={`${tabOverflowSuggestion.id}-${category}`}
                          >
                            {category}
                          </span>
                        ))
                      ) : (
                        <span className="border border-dashed border-zinc-300 px-2.5 py-1 text-xs">
                          No categories yet
                        </span>
                      )}
                    </div>
                  </footer>
                </div>
              </div>
              <button
                className="flex h-full w-6 cursor-pointer items-center justify-center rounded-none border-0 bg-transparent p-0 text-muted-foreground transition-colors hover:text-foreground sm:hidden"
                onClick={nextSuggestion}
                type="button"
              >
                <ChevronRight className="size-4" />
              </button>
            </div>

            <div className="mt-3 flex items-center justify-center gap-3">
              <button
                className="hidden cursor-pointer items-center justify-center rounded-none border-0 bg-transparent p-0 text-muted-foreground transition-colors hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40 sm:flex"
                disabled={currentIndex <= 0}
                onClick={previousSuggestion}
                type="button"
              >
                <ChevronLeft className="size-4" />
              </button>

              <span className="pointer-events-none font-mono text-[10px] font-semibold tracking-tight text-muted-foreground">
                {currentIndex >= 0 && suggestionHistory.length > 0
                  ? suggestionHistory[currentIndex] + 1
                  : 0}{" "}
                / {tabOverflowCount}
              </span>

              <button
                className="hidden cursor-pointer items-center justify-center rounded-none border-0 bg-transparent p-0 text-muted-foreground transition-colors hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40 sm:flex"
                onClick={nextSuggestion}
                type="button"
              >
                <ChevronRight className="size-4" />
              </button>
            </div>
          </div>
        )}

        <div className="border-t border-zinc-300 pt-4 dark:border-zinc-800">
        <div className="flex h-8 flex-wrap items-center justify-between gap-2">
          <button
            className="flex cursor-pointer items-center gap-1 border-0 p-0 text-xs font-semibold hover:text-primary"
            onClick={() => setIsTableVisible((value) => !value)}
            type="button"
          >
            {isTableVisible ? "hide all" : "show all"}
            {isTableVisible ? (
              <ChevronDown className="size-4" />
            ) : (
              <ChevronRight className="size-4" />
            )}
          </button>

          <div
            className={cn(
              "relative items-center gap-2",
              isTableVisible ? "flex" : "hidden"
            )}
            ref={readingTimeFilterRootRef}
          >
            {readingTimeFilterLabel ? (
              <span className="text-xs text-muted-foreground">
                under {readingTimeFilterLabel}
              </span>
            ) : null}

            <button
              className={cn(
                "cursor-pointer border-0 p-2",
                selectedReadingTimeFilter ? "bg-secondary" : "bg-transparent"
              )}
              onClick={() => setIsReadingTimeFilterOpen((value) => !value)}
              title="filter by read time"
              type="button"
            >
              <Hourglass className="size-4" />
            </button>

            {isReadingTimeFilterOpen ? (
              <div className="absolute right-0 top-full z-10 mt-2 min-w-[160px] rounded-md border border-zinc-300 bg-background/95 p-2 shadow-lg backdrop-blur-sm dark:border-zinc-800 dark:bg-zinc-900/95">
                <p className="px-1 pb-2 text-[11px] uppercase tracking-wide text-muted-foreground">
                  under
                </p>
                <div className="flex flex-col gap-1">
                  {readingTimeOptions.map((option) => (
                    <button
                      className={cn(
                        "cursor-pointer justify-start rounded-sm border-0 bg-transparent px-3 py-2 text-left text-xs capitalize",
                        option.value === selectedReadingTimeFilter
                          ? "bg-primary/10 text-primary hover:bg-primary/20"
                          : ""
                      )}
                      key={option.value}
                      onClick={() => {
                        setSelectedReadingTimeFilter((currentValue) =>
                          currentValue === option.value ? null : option.value
                        )
                        setIsReadingTimeFilterOpen(false)
                      }}
                      type="button"
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>
            ) : null}

            <button
              className={cn(
                "cursor-pointer border-0 px-2 py-1 text-xs",
                showOnlyBookmarked ? "bg-secondary" : "bg-transparent"
              )}
              onClick={() => setShowOnlyBookmarked((value) => !value)}
              title="filter by bookmarked"
              type="button"
            >
              <BookmarkCheck className="size-4" />
            </button>

            <span className="text-xs text-gray-500 dark:text-gray-400">
              {bookmarkCount} saved
            </span>
          </div>
        </div>
      </div>
      </div>

      {isTableVisible ? (
        <div className="mt-4 overflow-hidden border-zinc-300 dark:border-zinc-800">
          <div className="overflow-x-auto">
            <table className="w-full table-fixed caption-bottom text-sm">
                <colgroup>
                  <col className="w-[48%]" />
                  <col className="w-[11%]" />
                  <col className="w-[31%]" />
                  <col className="w-[10%]" />
                </colgroup>
                <tbody>
                  {filteredTableItems.length ? (
                    filteredTableItems.map((row) => (
                      <tr
                        className={cn(
                          "cursor-pointer border-b border-zinc-300/90 text-zinc-600 transition-colors hover:bg-zinc-300/80 dark:border-zinc-700/90 dark:text-zinc-400 dark:hover:bg-zinc-900/45",
                          row.item.id === tabOverflowSuggestion.id
                            ? "bg-zinc-200 dark:bg-zinc-900/60"
                            : ""
                        )}
                        key={row.item.id}
                        onClick={() => openSuggestionFromTable(row.index)}
                      >
                        <td className="truncate py-1.5 pr-5 text-sm font-medium lowercase text-zinc-800 dark:text-zinc-300">
                          {row.item.name}
                        </td>
                        <td className="px-2 py-1.5 text-sm">
                          {row.item.readingTime ? (
                            <span>{row.item.readingTime} min</span>
                          ) : (
                            <span className="opacity-70">—</span>
                          )}
                        </td>
                        <td className="px-2 py-1.5 lowercase">
                          <div className="no-scrollbar flex gap-1 overflow-hidden whitespace-nowrap">
                            {row.item.categories.length ? (
                              row.item.categories.map((category, index) => (
                                <span
                                  className="shrink-0 bg-zinc-100 px-3 py-[3px] text-[11px] font-medium text-zinc-800 dark:bg-zinc-800 dark:text-zinc-300"
                                  key={`${row.item.id}-cat-${index}`}
                                >
                                  {category}
                                </span>
                              ))
                            ) : (
                              <span className="text-xs opacity-70">—</span>
                            )}
                          </div>
                        </td>
                        <td className="px-4 py-1.5 text-right">
                          <div className="flex items-center justify-end gap-4">
                            <button
                              className="cursor-pointer border-0 bg-transparent p-0 transition-colors hover:text-zinc-800 dark:hover:text-zinc-300"
                              onClick={(event) => {
                                event.stopPropagation()
                                toggleBookmarkById(row.item.id)
                              }}
                              type="button"
                            >
                              {bookmarkedIds.includes(row.item.id) ? (
                                <BookmarkCheck className="size-4" />
                              ) : (
                                <Bookmark className="size-4" />
                              )}
                            </button>

                            <button
                              className="cursor-pointer border-0 bg-transparent p-0 transition-colors hover:text-zinc-800 dark:hover:text-zinc-300"
                              onClick={(event) => {
                                event.stopPropagation()
                                openLink(row.item.url)
                              }}
                              type="button"
                            >
                              <ArrowUpRight className="size-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td className="py-10 text-center" colSpan={4}>
                        <span className="text-sm text-gray-500 dark:text-gray-400">
                          No items to display. Try saving a bookmark first.
                        </span>
                      </td>
                    </tr>
                  )}
                </tbody>
            </table>
          </div>
        </div>
      ) : null}
    </div>
  )
}
