// src/pages/fun/tab-overflow/Index.vue
<template>
  <div
    class="min-h-80 flex flex-col shadow-md border border-gray-200 dark:border-gray-900 rounded-lg transition-all duration-1000 overflow-hidden"
  >
    <div
      v-if="isLoading"
      class="flex flex-1 gap-2 flex-col items-center justify-center h-full text-gray-600 dark:text-gray-400 transition-color duration-1000"
    >
      <p class="text-sm">Loading...</p>
      <Loader2 class="animate-spin size-6" />
    </div>

    <div
      v-else
      class="relative reading-suggestion gap-2 flex flex-col p-4 py-8 sm:p-6 flex-1"
    >
      <div
        class="absolute top-2 right-2 text-xs text-gray-500"
      >
        {{ currentItemNumber }} / {{ readingListCount }} on
        <a
          :href="`https://notion.so/fxn-m/${readingSuggestion.id.replace(
            /-/g,
            ''
          )}`"
          target="_blank"
          class="!text-inherit"
          >Notion</a
        >
      </div>

      <div class="card-content space-y-4 sm:space-y-6">
        <p>
          <a
            :href="readingSuggestion.url"
            target="_blank"
            class="text-lg sm:text-xl font-bold inline-flex items-start gap-1 break-words"
          >
            {{ readingSuggestion.name }}
            <ExternalLink
              class="inline-block size-3 flex-shrink-0 mt-1"
            />
          </a>
        </p>

        <p
          v-if="readingSuggestion.summary"
          class="mt-2 text-sm sm:text-base text-gray-700 dark:text-gray-500 line-clamp-6 sm:line-clamp-none"
        >
          {{ readingSuggestion.summary }}
        </p>

        <div
          class="flex flex-col sm:flex-row sm:items-center mt-3 sm:gap-2"
        >
          <p
            v-if="readingSuggestion.readingTime"
            class="text-xs sm:text-sm text-gray-600"
          >
            <span class="font-semibold">Reading Time:</span>
            {{ readingSuggestion.readingTime }} minutes
          </p>

          <div
            v-if="
              readingSuggestion.categories &&
              readingSuggestion.categories.length
            "
            class="flex flex-wrap gap-2 mt-2 sm:mt-0"
          >
            <span
              v-for="(
                category, index
              ) in readingSuggestion.categories"
              :key="index"
              class="bg-gray-200 text-gray-800 px-2 py-1 rounded-full text-xs dark:bg-gray-700 dark:text-gray-200 transition-colors duration-1000"
            >
              {{ category }}
            </span>
          </div>
        </div>
      </div>
      <!-- Navigation Arrows at the bottom -->
      <div
        class="flex flex-1 w-full justify-between items-end mt-4"
      >
        <button
          @click="prevSuggestion"
          class="text-gray-600 hover:text-gray-800 dark:text-gray-300 dark:hover:text-gray-400 p-2"
          :class="{
            'opacity-50 cursor-not-allowed':
              currentIndex === 0
          }"
          :disabled="currentIndex === 0"
        >
          <FontAwesomeIcon
            icon="fa-solid fa-arrow-left"
            size="lg"
          />
        </button>
        <button
          @click="nextSuggestion"
          class="text-gray-600 hover:text-gray-800 dark:text-gray-300 dark:hover:text-gray-400 p-2"
        >
          <FontAwesomeIcon
            icon="fa-solid fa-arrow-left"
            size="lg"
            class="rotate-180"
          />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import {
    ref,
    onMounted,
    onUnmounted,
    computed,
    watchEffect
  } from "vue"
  import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
  import { ExternalLink, Loader2 } from "lucide-vue-next"
  import { useQuery } from "@tanstack/vue-query"

  // Define the type for the reading suggestion based on the new schema
  interface ReadingSuggestion {
    id: string
    name: string // Guaranteed
    url: string // Guaranteed
    readingTime: number | null
    categories: string[]
    summary: string
  }

  // Define type for a reading list item
  interface ReadingListItem {
    id: string
    properties: {
      Name?: { title: { plain_text: string }[] }
      Link?: { url: string }
      "Read Time"?: { number: number }
      Categories?: { multi_select: { name: string }[] }
      Summary?: { rich_text: { plain_text: string }[] }
    }
  }

  // Reactive references
  const readingSuggestion = ref<ReadingSuggestion>({
    id: "",
    name: "",
    url: "",
    readingTime: null,
    categories: [],
    summary: ""
  })

  const fetchReadingList = async (): Promise<
    ReadingListItem[]
  > => {
    const response = await fetch(
      `${import.meta.env.VITE_BACKEND_URL}/readingList`,
      {
        method: "GET"
      }
    )

    if (!response.ok) {
      throw new Error("Network response was not ok")
    }

    return (await response.json()) as ReadingListItem[]
  }

  const { data, isLoading } = useQuery({
    queryKey: ["readingList"],
    queryFn: fetchReadingList,
    refetchOnWindowFocus: false
  })

  const readingList = computed(() => data.value ?? [])

  // History for navigation (storing indices) and pointer
  const suggestionHistory = ref<number[]>([])
  const currentIndex = ref(-1)

  const currentItemNumber = computed(() => {
    if (
      currentIndex.value >= 0 &&
      suggestionHistory.value.length > 0
    ) {
      return suggestionHistory.value[currentIndex.value] + 1
    }
    return 0
  })

  const readingListCount = computed(
    () => readingList.value.length
  )

  // Helper: Apply a suggestion from a given index
  const applySuggestionFromIndex = (index: number) => {
    const item = readingList.value[index]
    const props = item.properties || {}
    const name =
      props.Name?.title?.[0]?.plain_text || "Untitled"
    const url = props.Link?.url || "#"
    const readingTime = props["Read Time"]?.number || null
    const categories = props.Categories?.multi_select
      ? props.Categories.multi_select.map((cat) => cat.name)
      : []
    const summary = props.Summary?.rich_text
      ? props.Summary.rich_text
          .map((txt) => txt.plain_text)
          .join(" ")
      : ""

    readingSuggestion.value = {
      id: item.id,
      name,
      url,
      readingTime,
      categories,
      summary
    }
  }

  // Choose a random index from the reading list
  const chooseRandomIndex = (): number => {
    return Math.floor(
      Math.random() * readingList.value.length
    )
  }

  // Navigate to the next suggestion
  const nextSuggestion = () => {
    // If we've navigated back previously, move forward in history if possible
    if (
      currentIndex.value <
      suggestionHistory.value.length - 1
    ) {
      currentIndex.value++
      applySuggestionFromIndex(
        suggestionHistory.value[currentIndex.value]
      )
    } else {
      let randomIndex = chooseRandomIndex()
      // Avoid duplicate if possible
      if (
        suggestionHistory.value.length > 0 &&
        readingList.value.length > 1
      ) {
        while (
          randomIndex ===
          suggestionHistory.value[
            suggestionHistory.value.length - 1
          ]
        ) {
          randomIndex = chooseRandomIndex()
        }
      }
      suggestionHistory.value.push(randomIndex)
      currentIndex.value =
        suggestionHistory.value.length - 1
      applySuggestionFromIndex(randomIndex)
    }
  }

  // Navigate to the previous suggestion if available
  const prevSuggestion = () => {
    if (currentIndex.value > 0) {
      currentIndex.value--
      applySuggestionFromIndex(
        suggestionHistory.value[currentIndex.value]
      )
    }
  }

  // Key event listener for arrow keys
  const handleKeydown = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft") {
      prevSuggestion()
    } else if (e.key === "ArrowRight") {
      nextSuggestion()
    }
  }

  // Kick off the first suggestion once data is ready
  watchEffect(() => {
    if (
      !isLoading.value &&
      currentIndex.value === -1 &&
      readingListCount.value > 0
    ) {
      nextSuggestion()
    }
  })

  onMounted(() => {
    window.addEventListener("keydown", handleKeydown)
  })

  onUnmounted(() => {
    window.removeEventListener("keydown", handleKeydown)
  })
</script>

<style scoped>
  .reading-suggestion {
  line-height: 1.5;
}

button {
  background: none;
  border: none;
  cursor: pointer;
  touch-action: manipulation;
}

button {
  min-height: 44px;
  min-width: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>

// src/client/pages/tab-overflow.tsx
import { useQuery } from "@tanstack/react-query"
import {
  ArrowUpRight,
  Bookmark,
  BookmarkCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Hourglass
} from "lucide-react"
import { useEffect, useEffectEvent, useRef, useState } from "react"

import { cn } from "@/client/lib/utils"

type TabOverflowSuggestion = {
  added: Date | null
  categories: string[]
  id: string
  name: string
  readingTime: number | null
  summary: string
  url: string
}

type TabOverflowItem = {
  id: string
  properties: {
    Added?: { date?: { start?: string | null } | null; type: "date" }
    Categories?: { multi_select: { name: string }[] }
    Name?: { title: { plain_text: string }[] }
    "Read Time"?: { number: number }
    Summary?: { rich_text: { plain_text: string }[] }
    URL?: { url: string }
  }
}

const BOOKMARK_STORAGE_KEY = "tabOverflow:bookmarks"
const EMPTY_ITEMS: TabOverflowItem[] = []
const readingTimeOptions = [
  { label: "5 min", value: 5 },
  { label: "10 min", value: 10 },
  { label: "20 min", value: 20 }
] as const

type ReadingTimeValue = (typeof readingTimeOptions)[number]["value"]

function mapItemToSuggestion(item: TabOverflowItem): TabOverflowSuggestion {
  const props = item.properties ?? {}

  return {
    added:
      props.Added?.type === "date" && props.Added.date?.start
        ? new Date(props.Added.date.start)
        : null,
    categories:
      props.Categories?.multi_select?.map((category) => category.name) ?? [],
    id: item.id,
    name: props.Name?.title?.[0]?.plain_text || "Untitled",
    readingTime: props["Read Time"]?.number ?? null,
    summary:
      props.Summary?.rich_text?.map((text) => text.plain_text).join(" ") ?? "",
    url: props.URL?.url || "#"
  }
}

function loadBookmarks() {
  try {
    const stored = window.localStorage.getItem(BOOKMARK_STORAGE_KEY)

    if (!stored) {
      return []
    }

    const parsed = JSON.parse(stored)
    return Array.isArray(parsed)
      ? parsed.filter((value): value is string => typeof value === "string")
      : []
  } catch (error) {
    console.error("Failed to load Tab Overflow bookmarks", error)
    return []
  }
}

export default function TabOverflow() {
  const suggestionCardRef = useRef<HTMLDivElement | null>(null)
  const readingTimeFilterRootRef = useRef<HTMLDivElement | null>(null)
  const [bookmarkedIds, setBookmarkedIds] = useState<string[]>([])
  const [currentIndex, setCurrentIndex] = useState(-1)
  const [isReadingTimeFilterOpen, setIsReadingTimeFilterOpen] = useState(false)
  const [isTableVisible, setIsTableVisible] = useState(false)
  const [selectedReadingTimeFilter, setSelectedReadingTimeFilter] =
    useState<ReadingTimeValue | null>(null)
  const [showOnlyBookmarked, setShowOnlyBookmarked] = useState(false)
  const [suggestionHistory, setSuggestionHistory] = useState<number[]>([])
  const [tabOverflowSuggestion, setTabOverflowSuggestion] =
    useState<TabOverflowSuggestion>({
      added: null,
      categories: [],
      id: "",
      name: "",
      readingTime: null,
      summary: "",
      url: ""
    })

  const { data, isLoading } = useQuery({
    queryFn: async () => {
      const response = await fetch(
        `${import.meta.env.VITE_BACKEND_URL}/tab-overflow`
      )
      if (!response.ok) {
        throw new Error("Network response was not ok")
      }

      return (await response.json()) as TabOverflowItem[]
    },
    queryKey: ["tab-overflow"],
    refetchOnWindowFocus: false
  })

  const normalizedItems = (data ?? EMPTY_ITEMS).map(mapItemToSuggestion)
  const tabOverflowCount = normalizedItems.length
  const bookmarkCount = bookmarkedIds.length
  const isCurrentBookmarked = bookmarkedIds.includes(tabOverflowSuggestion.id)
  const readingTimeFilterLabel =
    readingTimeOptions.find(
      (option) => option.value === selectedReadingTimeFilter
    )?.label ?? ""

  const persistBookmarks = (nextBookmarkedIds: string[]) => {
    setBookmarkedIds(nextBookmarkedIds)
    window.localStorage.setItem(
      BOOKMARK_STORAGE_KEY,
      JSON.stringify(nextBookmarkedIds)
    )
  }

  const applySuggestionFromIndex = (index: number) => {
    const item = normalizedItems[index]
    if (item) {
      setTabOverflowSuggestion({ ...item })
    }
  }

  const chooseRandomIndex = () =>
    Math.floor(Math.random() * normalizedItems.length)

  const nextSuggestion = useEffectEvent(() => {
    if (!normalizedItems.length) {
      return
    }

    if (currentIndex < suggestionHistory.length - 1) {
      const nextIndex = currentIndex + 1
      setCurrentIndex(nextIndex)
      applySuggestionFromIndex(suggestionHistory[nextIndex])
      return
    }

    let randomIndex = chooseRandomIndex()
    if (suggestionHistory.length > 0 && normalizedItems.length > 1) {
      while (randomIndex === suggestionHistory[suggestionHistory.length - 1]) {
        randomIndex = chooseRandomIndex()
      }
    }

    const nextHistory = [...suggestionHistory, randomIndex]
    setSuggestionHistory(nextHistory)
    setCurrentIndex(nextHistory.length - 1)
    applySuggestionFromIndex(randomIndex)
  })

  const previousSuggestion = useEffectEvent(() => {
    if (currentIndex <= 0) {
      return
    }

    const nextIndex = currentIndex - 1
    setCurrentIndex(nextIndex)
    applySuggestionFromIndex(suggestionHistory[nextIndex])
  })

  const openLink = (url: string) => {
    if (!url || url === "#") {
      return
    }

    window.open(url, "_blank", "noopener")
  }

  const toggleBookmarkById = (id: string) => {
    if (!id) {
      return
    }

    if (bookmarkedIds.includes(id)) {
      persistBookmarks(bookmarkedIds.filter((bookmarkId) => bookmarkId !== id))
    } else {
      persistBookmarks([...bookmarkedIds, id])
    }
  }

  const filteredTableItems = normalizedItems
    .map((item, index) => ({ index, item }))
    .filter(({ item }) =>
      showOnlyBookmarked ? bookmarkedIds.includes(item.id) : true
    )
    .filter(({ item }) => {
      if (selectedReadingTimeFilter === null) {
        return true
      }

      if (typeof item.readingTime !== "number") {
        return false
      }

      return item.readingTime < selectedReadingTimeFilter
    })
    .sort(
      (a, b) => (b.item.added?.getTime() ?? 0) - (a.item.added?.getTime() ?? 0)
    )

  const scrollToSuggestionCard = () => {
    if (!suggestionCardRef.current) {
      window.scrollTo({ behavior: "smooth", top: 0 })
      return
    }

    const rect = suggestionCardRef.current.getBoundingClientRect()
    const viewportCenter = window.innerHeight / 2
    const target = window.scrollY + rect.top + rect.height / 2 - viewportCenter
    window.scrollTo({
      behavior: "smooth",
      top: target > 0 ? target : 0
    })
  }

  const openSuggestionFromTable = (index: number) => {
    if (index < 0 || index >= normalizedItems.length) {
      return
    }

    const nextHistory =
      suggestionHistory[suggestionHistory.length - 1] === index
        ? suggestionHistory
        : [...suggestionHistory, index]

    setSuggestionHistory(nextHistory)
    setCurrentIndex(nextHistory.length - 1)
    applySuggestionFromIndex(index)
    window.requestAnimationFrame(scrollToSuggestionCard)
  }

  useEffect(() => {
    setBookmarkedIds(loadBookmarks())
  }, [])

  useEffect(() => {
    const availableIds = new Set(normalizedItems.map((item) => item.id))
    const filteredBookmarks = bookmarkedIds.filter((id) => availableIds.has(id))
    if (filteredBookmarks.length !== bookmarkedIds.length) {
      persistBookmarks(filteredBookmarks)
    }
  }, [bookmarkedIds, normalizedItems])

  useEffect(() => {
    if (!isLoading && currentIndex === -1 && tabOverflowCount > 0) {
      nextSuggestion()
    }
  }, [currentIndex, isLoading, nextSuggestion, tabOverflowCount])

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if (event.key === "ArrowLeft") {
        previousSuggestion()
      }

      if (event.key === "ArrowRight") {
        nextSuggestion()
      }
    }

    const handleDocumentClick = (event: MouseEvent) => {
      if (
        isReadingTimeFilterOpen &&
        readingTimeFilterRootRef.current &&
        !readingTimeFilterRootRef.current.contains(event.target as Node)
      ) {
        setIsReadingTimeFilterOpen(false)
      }
    }

    window.addEventListener("keydown", handleKeydown)
    document.addEventListener("click", handleDocumentClick)

    return () => {
      window.removeEventListener("keydown", handleKeydown)
      document.removeEventListener("click", handleDocumentClick)
    }
  }, [isReadingTimeFilterOpen, nextSuggestion, previousSuggestion])

  return (
    <div className="flex min-h-[calc(100vh-8rem)] flex-col overflow-hidden transition-all duration-1000">
      <div className="flex min-h-[calc(100vh-12rem)] shrink-0 flex-col">
        {isLoading ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-4 py-8 transition-colors duration-1000">
            <div className="w-full">
              <div className="animate-pulse">
                <div className="h-4 w-24 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-6 h-6 w-3/4 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-3 h-4 w-full rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-2 h-4 w-5/6 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-2 h-4 w-1/2 rounded bg-gray-200 dark:bg-gray-700" />
                <div className="mt-6 flex flex-wrap gap-2">
                  <span className="block h-6 w-20 bg-gray-200 dark:bg-gray-700" />
                  <span className="block h-6 w-16 bg-gray-200 dark:bg-gray-700" />
                </div>
                <div className="mt-6 flex flex-wrap gap-2">
                  <span className="block h-9 w-28 bg-gray-200 dark:bg-gray-700" />
                  <span className="block h-9 w-28 bg-gray-200 dark:bg-gray-700" />
                  <span className="block h-9 w-32 bg-gray-200 dark:bg-gray-700" />
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div
            className="flex flex-1 flex-col items-center justify-center gap-2 py-8"
            ref={suggestionCardRef}
          >
            <div className="w-full">
              <div className="relative flex h-full w-full min-w-0 flex-col overflow-hidden border-0 bg-transparent">
                <div className="flex h-full w-full min-w-0 flex-col">
                  <header className="flex w-full min-w-0 flex-nowrap items-center gap-4 overflow-hidden">
                    <a
                      className="block min-w-0 flex-1 truncate text-md font-medium lowercase leading-tight text-foreground transition-colors hover:text-primary sm:text-lg"
                      href={tabOverflowSuggestion.url}
                      rel="noreferrer noopener"
                      target="_blank"
                    >
                      {tabOverflowSuggestion.name}
                    </a>

                    <div className="flex shrink-0 items-center gap-2">
                      <button
                        className="cursor-pointer rounded-none  bg-secondary p-2 text-foreground transition hover:bg-primary/10 dark:border-zinc-800"
                        onClick={() => openLink(tabOverflowSuggestion.url)}
                        title="open in new tab"
                        type="button"
                      >
                        <ArrowUpRight className="size-4" />
                      </button>

                      <button
                        className={cn(
                          "cursor-pointer rounded-none border p-2 transition",
                          isCurrentBookmarked
                            ? "border-primary/40 bg-primary/10 text-primary"
                            : "border-transparent bg-transparent text-foreground hover:border-primary/40"
                        )}
                        onClick={() =>
                          toggleBookmarkById(tabOverflowSuggestion.id)
                        }
                        title={
                          isCurrentBookmarked
                            ? "remove bookmark"
                            : "save for later"
                        }
                        type="button"
                      >
                        {isCurrentBookmarked ? (
                          <BookmarkCheck className="size-4" />
                        ) : (
                          <Bookmark className="size-4" />
                        )}
                      </button>
                    </div>
                  </header>

                  <section className="min-w-0 py-1">
                    {tabOverflowSuggestion.summary ? (
                      <p className="min-h-[5lh] line-clamp-5 text-sm leading-relaxed text-muted-foreground sm:text-base">
                        {tabOverflowSuggestion.summary}
                      </p>
                    ) : (
                      <p className="text-sm italic text-muted-foreground">
                        No summary available for this suggestion yet.
                      </p>
                    )}
                  </section>

                  <footer className="flex min-w-0 flex-col gap-3 py-1 text-xs text-muted-foreground sm:flex-row sm:items-center sm:gap-4">
                    <div className="flex shrink-0 flex-wrap items-center gap-1">
                      <span className="font-medium text-foreground">
                        reading time:
                      </span>
                      <span>
                        {tabOverflowSuggestion.readingTime
                          ? `${tabOverflowSuggestion.readingTime} minutes`
                          : "Not set"}
                      </span>
                    </div>

                    <div className="no-scrollbar w-full min-w-0 overflow-x-auto sm:ml-auto sm:w-auto sm:max-w-[60%]">
                      <div className="flex w-max min-w-full flex-nowrap gap-2 sm:justify-end">
                        {tabOverflowSuggestion.categories.length ? (
                          tabOverflowSuggestion.categories.map((category) => (
                            <span
                              className="shrink-0 border border-zinc-300 px-2.5 py-1 text-xs font-medium lowercase text-foreground dark:border-zinc-700"
                              key={`${tabOverflowSuggestion.id}-${category}`}
                            >
                              {category}
                            </span>
                          ))
                        ) : (
                          <span className="shrink-0 border border-dashed border-zinc-300 px-2.5 py-1 text-xs">
                            No categories yet
                          </span>
                        )}
                      </div>
                    </div>
                  </footer>
                </div>
              </div>
            </div>

            <div className="mt-3 flex items-center justify-center gap-3">
              <button
                className="flex min-h-10 min-w-10 cursor-pointer items-center justify-center rounded-md border border-zinc-300/80 px-3 py-2 text-muted-foreground transition-colors hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40 dark:border-zinc-800 sm:min-h-0 sm:min-w-0 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0"
                disabled={currentIndex <= 0}
                onClick={previousSuggestion}
                type="button"
              >
                <ChevronLeft className="size-4" />
              </button>

              <span className="pointer-events-none font-mono text-[10px] font-semibold tracking-tight text-muted-foreground">
                {String(
                  currentIndex >= 0 && suggestionHistory.length > 0
                    ? suggestionHistory[currentIndex] + 1
                    : 0
                ).padStart(3, "0")}{" "}
                / {tabOverflowCount}
              </span>

              <button
                className="flex min-h-10 min-w-10 cursor-pointer items-center justify-center rounded-md border border-zinc-300/80 px-3 py-2 text-muted-foreground transition-colors hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40 dark:border-zinc-800 sm:min-h-0 sm:min-w-0 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0"
                onClick={nextSuggestion}
                type="button"
              >
                <ChevronRight className="size-4" />
              </button>
            </div>
          </div>
        )}

        <div className="border-t border-zinc-300 pt-4 dark:border-zinc-800">
        <div className="flex h-8 flex-wrap items-center justify-between gap-2">
          <button
            className="flex cursor-pointer items-center gap-1 border-0 p-0 text-xs font-semibold hover:text-primary"
            onClick={() => setIsTableVisible((value) => !value)}
            type="button"
          >
            {isTableVisible ? "hide all" : "show all"}
            {isTableVisible ? (
              <ChevronDown className="size-4" />
            ) : (
              <ChevronRight className="size-4" />
            )}
          </button>

          <div
            className={cn(
              "relative items-center gap-2",
              isTableVisible ? "flex" : "hidden"
            )}
            ref={readingTimeFilterRootRef}
          >
            {readingTimeFilterLabel ? (
              <span className="text-xs text-muted-foreground">
                under {readingTimeFilterLabel}
              </span>
            ) : null}

            <button
              className={cn(
                "cursor-pointer border-0 p-2",
                selectedReadingTimeFilter ? "bg-secondary" : "bg-transparent"
              )}
              onClick={() => setIsReadingTimeFilterOpen((value) => !value)}
              title="filter by read time"
              type="button"
            >
              <Hourglass className="size-4" />
            </button>

            {isReadingTimeFilterOpen ? (
              <div className="absolute right-0 top-full z-10 mt-2 min-w-[160px] rounded-md border border-zinc-300 bg-background/95 p-2 shadow-lg backdrop-blur-sm dark:border-zinc-800 dark:bg-zinc-900/95">
                <p className="px-1 pb-2 text-[11px] uppercase tracking-wide text-muted-foreground">
                  under
                </p>
                <div className="flex flex-col gap-1">
                  {readingTimeOptions.map((option) => (
                    <button
                      className={cn(
                        "cursor-pointer justify-start rounded-sm border-0 bg-transparent px-3 py-2 text-left text-xs capitalize",
                        option.value === selectedReadingTimeFilter
                          ? "bg-primary/10 text-primary hover:bg-primary/20"
                          : ""
                      )}
                      key={option.value}
                      onClick={() => {
                        setSelectedReadingTimeFilter((currentValue) =>
                          currentValue === option.value ? null : option.value
                        )
                        setIsReadingTimeFilterOpen(false)
                      }}
                      type="button"
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>
            ) : null}

            <button
              className={cn(
                "cursor-pointer border-0 px-2 py-1 text-xs",
                showOnlyBookmarked ? "bg-secondary" : "bg-transparent"
              )}
              onClick={() => setShowOnlyBookmarked((value) => !value)}
              title="filter by bookmarked"
              type="button"
            >
              <BookmarkCheck className="size-4" />
            </button>

            <span className="text-xs text-gray-500 dark:text-gray-400">
              {bookmarkCount} saved
            </span>
          </div>
        </div>
      </div>
      </div>

      {isTableVisible ? (
        <div className="mt-4 overflow-hidden border-zinc-300 dark:border-zinc-800">
          <div className="overflow-x-auto">
            <table className="w-full table-fixed caption-bottom text-sm">
                <colgroup>
                  <col className="w-[calc(100%-128px)] sm:w-[48%]" />
                  <col className="w-[56px] sm:w-[72px]" />
                  <col className="hidden sm:table-column sm:w-[calc(52%-160px)]" />
                  <col className="w-[72px] sm:w-[88px]" />
                </colgroup>
                <tbody>
                  {filteredTableItems.length ? (
                    filteredTableItems.map((row) => (
                      <tr
                        className={cn(
                          "cursor-pointer border-b border-zinc-300/90 text-zinc-600 transition-colors hover:bg-zinc-300/80 dark:border-zinc-700/90 dark:text-zinc-400 dark:hover:bg-zinc-900/45",
                          row.item.id === tabOverflowSuggestion.id
                            ? "bg-zinc-200 dark:bg-zinc-900/60"
                            : ""
                        )}
                        key={row.item.id}
                        onClick={() => openSuggestionFromTable(row.index)}
                      >
                        <td className="overflow-hidden py-1.5 pr-5 text-sm font-medium lowercase text-zinc-800 dark:text-zinc-300">
                          <div className="truncate">{row.item.name}</div>
                        </td>
                        <td className="px-2 py-1.5 text-sm">
                          {row.item.readingTime ? (
                            <span>{row.item.readingTime} min</span>
                          ) : (
                            <span className="opacity-70">—</span>
                          )}
                        </td>
                        <td className="hidden overflow-hidden px-2 py-1.5 lowercase sm:table-cell">
                          <div className="no-scrollbar w-full min-w-0 max-w-full overflow-x-auto overflow-y-hidden">
                            <div className="inline-flex flex-nowrap gap-1">
                              {row.item.categories.length ? (
                                row.item.categories.map((category, index) => (
                                  <span
                                    className="shrink-0 bg-zinc-100 px-3 py-[3px] text-[11px] font-medium text-zinc-800 dark:bg-zinc-800 dark:text-zinc-300"
                                    key={`${row.item.id}-cat-${index}`}
                                  >
                                    {category}
                                  </span>
                                ))
                              ) : (
                                <span className="shrink-0 text-xs opacity-70">—</span>
                              )}
                            </div>
                          </div>
                        </td>
                        <td className="relative z-10 px-2 py-1.5 text-right sm:px-4">
                          <div className="flex items-center justify-end gap-3 sm:gap-4">
                            <button
                              className="cursor-pointer border-0 bg-transparent p-0 transition-colors hover:text-zinc-800 dark:hover:text-zinc-300"
                              onClick={(event) => {
                                event.stopPropagation()
                                toggleBookmarkById(row.item.id)
                              }}
                              type="button"
                            >
                              {bookmarkedIds.includes(row.item.id) ? (
                                <BookmarkCheck className="size-4" />
                              ) : (
                                <Bookmark className="size-4" />
                              )}
                            </button>

                            <button
                              className="cursor-pointer border-0 bg-transparent p-0 transition-colors hover:text-zinc-800 dark:hover:text-zinc-300"
                              onClick={(event) => {
                                event.stopPropagation()
                                openLink(row.item.url)
                              }}
                              type="button"
                            >
                              <ArrowUpRight className="size-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td className="py-10 text-center" colSpan={4}>
                        <span className="text-sm text-gray-500 dark:text-gray-400">
                          No items to display. Try saving a bookmark first.
                        </span>
                      </td>
                    </tr>
                  )}
                </tbody>
            </table>
          </div>
        </div>
      ) : null}
    </div>
  )
}
