// src/client/components/theme/theme-toggle.tsx
import { useState } from "react"

import { cn } from "@/client/lib/utils"

import { useTheme } from "./theme-provider"

export default function ThemeToggle({
  className,
  isMobileMenuOpen = false
}: {
  className?: string
  isMobileMenuOpen?: boolean
}) {
  const { resolvedTheme, theme, toggleTheme } = useTheme()
  const [showTooltip, setShowTooltip] = useState(false)
  const iconSrc =
    resolvedTheme === "dark" ? "/dark-mode.svg" : "/light-mode.svg"
  const iconId = resolvedTheme === "dark" ? "dark-mode-icon" : "light-mode-icon"

  return (
    <div className="relative flex size-10 items-center justify-start">
      <button
        className={cn(
          "flex h-full w-full cursor-pointer items-center justify-center rounded-full border-0 p-[5px] transition-colors duration-200",
          isMobileMenuOpen
            ? "bg-zinc-200/60 dark:bg-zinc-800/60"
            : "bg-transparent",
          className
        )}
        onMouseEnter={() => setShowTooltip(true)}
        onMouseLeave={() => setShowTooltip(false)}
        onClick={toggleTheme}
        title={theme}
        type="button"
      >
        <img
          alt={theme}
          className={cn(
            "size-[28px] transition-[filter,transform] duration-500",
            iconId === "dark-mode-icon"
              ? "scale-[1.3] [filter:invert(69%)_sepia(10%)_saturate(17%)_hue-rotate(318deg)_brightness(84%)_contrast(87%)] hover:[filter:invert(100%)_sepia(0%)_saturate(0%)_hue-rotate(0deg)_brightness(100%)_contrast(100%)]"
              : "[filter:invert(33%)_sepia(0%)_saturate(15%)_hue-rotate(279deg)_brightness(102%)_contrast(91%)] hover:[filter:invert(0%)_sepia(0%)_saturate(0%)_hue-rotate(0deg)_brightness(100%)_contrast(100%)]"
          )}
          src={iconSrc}
        />
        {showTooltip ? (
          <span
            className={cn(
              "pointer-events-none absolute z-[1000] whitespace-nowrap rounded text-[12px] text-[#777] dark:text-[#aaa]",
              isMobileMenuOpen ? "-translate-y-[35px]" : "translate-x-[40px]"
            )}
          >
            {theme}
          </span>
        ) : null}
      </button>
    </div>
  )
}

// src/client/components/theme/ThemeToggle.vue
<template>
  <div class="theme-toggle-wrapper">
    <button
      :class="buttonClasses"
      :title="tooltipText"
      @click="toggleTheme"
      @mouseenter="showTooltip = true"
      @mouseleave="showTooltip = false"
      class="size-[40px] p-[5px]"
    >
      <img v-if="iconSrc" :id="iconId" :src="iconSrc" :alt="tooltipText" />
      <span v-if="showTooltip" :class="tooltipClasses">{{ tooltipText }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
  import { computed, onMounted, ref, watch } from "vue"

  import { theme } from "./themeState"

  const props = withDefaults(
    defineProps<{
      isMobileMenuOpen?: boolean
    }>(),
    {
      isMobileMenuOpen: false
    }
  )

  const buttonClasses = computed(() => [
    "w-full h-full flex items-center justify-center rounded-full transition-colors duration-200",
    props.isMobileMenuOpen
      ? "bg-zinc-200/60 dark:bg-zinc-800/60"
      : "bg-transparent"
  ])

  const tooltipClasses = computed(() => [
    "tooltip",
    props.isMobileMenuOpen ? "-translate-y-[35px] " : "translate-x-[40px]"
  ])

  const showTooltip = ref(false)
  const tooltipText = computed(() => `${theme.value}`)

  const currentIconSrc = ref("/light-mode.svg")
  const currentIconId = ref("light-mode-icon")

  const toggleTheme = () => {
    theme.value =
      theme.value === "system"
        ? "dark"
        : theme.value === "dark"
          ? "light"
          : "system"
    sessionStorage.setItem("theme", theme.value)
    updateBodyClass()
  }

  const updateBodyClass = () => {
    const isDark =
      theme.value === "dark" ||
      (theme.value === "system" &&
        window.matchMedia("(prefers-color-scheme: dark)").matches)
    document.body.classList.toggle("dark", isDark)

    currentIconSrc.value = isDark ? "/dark-mode.svg" : "/light-mode.svg"
    currentIconId.value = isDark ? "dark-mode-icon" : "light-mode-icon"
  }

  const iconSrc = computed(() => currentIconSrc.value)
  const iconId = computed(() => currentIconId.value)

  onMounted(() => {
    const darkColorSchemeQuery = window.matchMedia(
      "(prefers-color-scheme: dark)"
    )

    if (!sessionStorage.getItem("theme")) {
      theme.value = "system"
    }

    updateBodyClass()

    darkColorSchemeQuery.addEventListener("change", updateBodyClass)

    const favicon = document.querySelector(
      "link[rel='icon']"
    ) as HTMLLinkElement
    const toggleFavicon = () => {
      const isDark =
        theme.value === "dark" ||
        (theme.value === "system" && darkColorSchemeQuery.matches)
      favicon.setAttribute(
        "href",
        isDark ? "/favicon-dark.png" : "/favicon.png"
      )
    }

    toggleFavicon()
    watch(theme, () => {
      toggleFavicon()
      updateBodyClass()
    })
  })
</script>

<style scoped>
  button {
    border: none;
    cursor: pointer;
    justify-content: center;
  }

  .theme-toggle-wrapper {
    position: relative;
    display: flex;
    justify-content: start;
    align-items: center;
    height: 40px;
    width: 40px;
  }

  .tooltip {
    position: absolute;
    border-radius: 4px;
    font-size: 12px;
    white-space: nowrap;
    z-index: 1000;
    text-align: center;
    color: #777;
  }

  body.dark .tooltip {
    color: #aaa;
  }

  /* // dark mode toggle styling */

  #dark-mode-icon {
    filter: invert(69%) sepia(10%) saturate(17%) hue-rotate(318deg)
      brightness(84%) contrast(87%);
    transform: scale(1.3);
    transition: filter 0.5s ease-in-out;
  }

  #dark-mode-icon:hover {
    filter: invert(100%) sepia(0%) saturate(0%) hue-rotate(0deg)
      brightness(100%) contrast(100%);
  }

  #light-mode-icon {
    filter: invert(33%) sepia(0%) saturate(15%) hue-rotate(279deg)
      brightness(102%) contrast(91%);
    transition: filter 0.5s ease-in-out;
  }

  #light-mode-icon:hover {
    filter: invert(0%) sepia(0%) saturate(0%) hue-rotate(0deg) brightness(100%)
      contrast(100%);
  }
</style>
